TYPE=VIEW
query=select coalesce(`s1`.`sum(masuk1)`,0) AS `summasuk1`,coalesce(`s3`.`sumretur`,0) AS `sumretur`,`b`.`Kode_brg` AS `kode_brg`,`b`.`Deskripsi` AS `deskripsi`,coalesce((`v1`.`masuk1` - `v1`.`keluar1`),0) AS `masuk1`,coalesce(`v3`.`retur`,0) AS `retur`,coalesce(`v2`.`terjual`,0) AS `terjual`,`b`.`Stok` AS `stok`,coalesce(`s2`.`sum(terjual)`,0) AS `sum(terjual)`,(((`b`.`Stok` + coalesce(`s2`.`sum(terjual)`,0)) - coalesce(`s1`.`sum(masuk1)`,0)) - coalesce(`s3`.`sumretur`,0)) AS `stokakhir`,((((((`b`.`Stok` + coalesce(`s2`.`sum(terjual)`,0)) - coalesce(`s1`.`sum(masuk1)`,0)) - coalesce(`s3`.`sumretur`,0)) + coalesce(`v2`.`terjual`,0)) - coalesce((`v1`.`masuk1` - `v1`.`keluar1`),0)) - coalesce(`v3`.`retur`,0)) AS `stokawl` from ((((((`apotek1`.`tblbarang` `B` left join `apotek1`.`vsesuai` `v1` on(((`b`.`Kode_brg` = `v1`.`Kode_brg`) and (`v1`.`tanggal` = _utf8\'2014-05-01\')))) left join `apotek1`.`vretur` `v3` on(((`b`.`Kode_brg` = `v3`.`kode_brg`) and (`v3`.`tanggal` = _utf8\'2014-05-01\')))) left join `apotek1`.`vpenjualan` `v2` on(((`v2`.`kode_brg` = `b`.`Kode_brg`) and (`v2`.`tanggal` = _utf8\'2014-05-01\')))) left join `apotek1`.`summasuk1` `s1` on((`s1`.`kode_brg` = `b`.`Kode_brg`))) left join `apotek1`.`vsumkeluar` `s2` on((`s2`.`kode_brg` = `b`.`Kode_brg`))) left join `apotek1`.`vsumretur` `s3` on((`s3`.`kode_brg` = `b`.`Kode_brg`))) group by `b`.`Kode_brg`
md5=31037e74b6671a64845cd3a3164c4924
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
revision=1
timestamp=2015-05-03 13:33:21
create-version=1
source=select coalesce(`s1`.`sum(masuk1)`,0) AS `summasuk1`,coalesce(`s3`.`sumretur`,0) AS `sumretur`,`b`.`Kode_brg` AS `kode_brg`,`b`.`Deskripsi` AS `deskripsi`,coalesce((`v1`.`masuk1` - `v1`.`keluar1`),0) AS `masuk1`,coalesce(`v3`.`retur`,0) AS `retur`,coalesce(`v2`.`terjual`,0) AS `terjual`,`b`.`Stok` AS `stok`,coalesce(`s2`.`sum(terjual)`,0) AS `sum(terjual)`,(((`b`.`Stok` + coalesce(`s2`.`sum(terjual)`,0)) - coalesce(`s1`.`sum(masuk1)`,0)) - coalesce(`s3`.`sumretur`,0)) AS `stokakhir`,((((((`b`.`Stok` + coalesce(`s2`.`sum(terjual)`,0)) - coalesce(`s1`.`sum(masuk1)`,0)) - coalesce(`s3`.`sumretur`,0)) + coalesce(`v2`.`terjual`,0)) - coalesce((`v1`.`masuk1` - `v1`.`keluar1`),0)) - coalesce(`v3`.`retur`,0)) AS `stokawl` from ((((((`tblbarang` `B` left join `vsesuai` `v1` on(((`b`.`Kode_brg` = `v1`.`Kode_brg`) and (`v1`.`tanggal` = _utf8\'2014-05-01\')))) left join `vretur` `v3` on(((`b`.`Kode_brg` = `v3`.`kode_brg`) and (`v3`.`tanggal` = _utf8\'2014-05-01\')))) left join `vpenjualan` `v2` on(((`v2`.`kode_brg` = `b`.`Kode_brg`) and (`v2`.`tanggal` = _utf8\'2014-05-01\')))) left join `summasuk1` `s1` on((`s1`.`kode_brg` = `b`.`Kode_brg`))) left join `vsumkeluar` `s2` on((`s2`.`kode_brg` = `b`.`Kode_brg`))) left join `vsumretur` `s3` on((`s3`.`kode_brg` = `b`.`Kode_brg`))) group by `b`.`Kode_brg`
